/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DrawHistoryRouteImport } from './routes/draw-history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CharitiesRouteImport } from './routes/charities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawHistoryRoute = DrawHistoryRouteImport.update({
  id: '/draw-history',
  path: '/draw-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CharitiesRoute = CharitiesRouteImport.update({
  id: '/charities',
  path: '/charities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/charities': typeof CharitiesRoute
  '/dashboard': typeof DashboardRoute
  '/draw-history': typeof DrawHistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/charities': typeof CharitiesRoute
  '/dashboard': typeof DashboardRoute
  '/draw-history': typeof DrawHistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/charities': typeof CharitiesRoute
  '/dashboard': typeof DashboardRoute
  '/draw-history': typeof DrawHistoryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/charities'
    | '/dashboard'
    | '/draw-history'
    | '/login'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/charities'
    | '/dashboard'
    | '/draw-history'
    | '/login'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/charities'
    | '/dashboard'
    | '/draw-history'
    | '/login'
    | '/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CharitiesRoute: typeof CharitiesRoute
  DashboardRoute: typeof DashboardRoute
  DrawHistoryRoute: typeof DrawHistoryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw-history': {
      id: '/draw-history'
      path: '/draw-history'
      fullPath: '/draw-history'
      preLoaderRoute: typeof DrawHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charities': {
      id: '/charities'
      path: '/charities'
      fullPath: '/charities'
      preLoaderRoute: typeof CharitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CharitiesRoute: CharitiesRoute,
  DashboardRoute: DashboardRoute,
  DrawHistoryRoute: DrawHistoryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
